spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esercitazione
    username: root
    password: 14011998
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
