server:
  port: 5000

---
spring:
  config:
    activate:
      on-profile: test
name: test-YAML
environment: testing
enabled: false
servers:
  port: 4000

---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
enabled: true
servers:
  port: 7070